name: SCC Complexity Check

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  scc-check:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-scc') }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: aziontech/scc_check@main
